[package]
name = "rt_reflections"
version = "0.1.0"
edition = "2021"
authors = ["Maarten Behn <maarten.behn@gmail.com>"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
app = { path = "../../libs/lagecy/app"}
gltf = { path = "../../libs/gltf" }