[package]
name = "vulkan_rust"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
simplelog = "0.12.0"
winit = "0.27.0"
ash = "0.37.0" 
ash-window = "0.10.0"
cgmath = "0.18"
image = "0.24.1"
ahash = "0.8.3"
delaunator = "1.0.1"
rand = "0.8.5"
spherical_voronoi = "0.5.1"
rand_distr = "0.4.3"
game-loop = { version = "0.10.1", features = ["winit"] }
extend = "1.1.2"
imgui = "0.10.0"
imgui-rs-vulkan-renderer = "1.8.0"
imgui-winit-support = "0.10.0"