[package]
name = "vulkan_rust"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
simplelog = "0.11.2"
tobj = "2.0.1"
delaunator = "1.0.1"
rand = "0.8.5"
spherical_voronoi = "0.5.1"
rand_distr = "0.4.3"
extend = "1.1.2"


ash = "0.37.0" 
ash-window = "0.10.0"
cgmath = "0.18"
image = "0.24.1"
ahash = "0.7.6"
winit = "0.26.1"
game-loop = { version = "0.8.2", features = ["window"] }
imgui = "0.8.2"
imgui-rs-vulkan-renderer = "1.2.0"
imgui-winit-support = { version = "^0.8", default-features = false, features = ["winit-26"] }

