[package]
name = "vulkan_rust"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
simplelog = "0.11.2"
ash = "0.36.0" 
ash-window = "0.9.0"
cgmath = "0.18"
image = "0.24.1"
ahash = "0.7.6"
winit = "0.26.1"
game-loop = { version = "0.8.2", features = ["window"] }