[package]
name = "astrinder"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
app = { path = "../../libs/app" }

collision.workspace = true
cgmath.workspace = true
noise.workspace = true
fps_clock.workspace = true
rand.workspace = true