[package]
name = "astrinder"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
app = { path = "../../libs/app" }

collision.workspace = true
cgmath.workspace = true
geo.workspace = true