#version 450
#extension GL_EXT_shader_16bit_storage: enable
#extension GL_EXT_shader_explicit_arithmetic_types_float16: enable

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

struct Node{
    uint16_t children[8];
    uint16_t parent;
    uint16_t data;
    vec3 color;
};

layout(binding = 0) buffer OcttreeBuffer {
    Node octtree[];
} octtreeBuffer;


void main()
{
    uvec3 pos = gl_GlobalInvocationID.xyz;
}