#version 450

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(binding = 0, rgba8) uniform writeonly image2D img;
layout(binding = 1) uniform UniformBufferObject {
    vec2 screen_size;
    vec3 pos;
    vec3 dir;
} ubo;


void main () {

    // Normalized pixel coordinates (from 0 to 1)
    vec2 uv = gl_GlobalInvocationID.xy / ubo.screen_size;
    
    imageStore(img, ivec2(gl_GlobalInvocationID.xy), vec4(uv, 0, 0));
}

