[package]
name = "octtree_builder_v2"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
fastrand.workspace = true
indicatif.workspace = true


octa-force.workspace = true
octtree_v2 = { path = "../../libs/octtree_v2" }